# -*- coding: utf-8 -*-
# Deployment settings for test1.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['/Developer/Marmalade/5.2/s3e/makefile_builder/mkb.py', '--buildenv=xcode', '/Users/danielshir/Work/InnoBell/s3eNextpeerTest/test1.mkb', '--deploy-only']
mkb = '/Users/danielshir/Work/InnoBell/s3eNextpeerTest/test1.mkb'
mkf = ['/Developer/Marmalade/5.2/extensions/s3eNextpeer/s3eNextpeer.mkf', '/Developer/Marmalade/5.2/modules/iwutil/iwutil.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('/Users/danielshir/Work/InnoBell/s3eNextpeerTest/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'test1'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'test1'
    long_caption = 'test1'
    version = [0, 0, 1]
    config = ['/Users/danielshir/Work/InnoBell/s3eNextpeerTest/data/app.icf']
    data_dir = '/Users/danielshir/Work/InnoBell/s3eNextpeerTest/data'
    linux_ext_lib = []
    iphone_link_opts = ['-weak_framework UIKit -weak_framework Security -lsqlite3.0']
    osx_ext_dll = ['/Developer/Marmalade/5.2/extensions/s3eNextpeer/lib/osx/libs3eNextpeer.dylib']
    android_external_jars = []
    android_external_res = []
    android_supports_gl_texture = []
    iphone_nosign = 0
    android_extra_manifest = []
    iphone_link_libdirs = ['/Developer/Marmalade/5.2/extensions/s3eNextpeer/lib/iphone']
    android_extra_application_manifest = []
    win32_ext_dll = []
    android_so = []
    iphone_signing_identity = 'iPhone Developer'
    iphone_no_splash = 1
    iphone_link_libs = ['s3eNextpeer']
    target = {
         'arm_gcc' : {
                   'debug'   : '/Users/danielshir/Work/InnoBell/s3eNextpeerTest/build_test1_xcode/build/Debug ARM/test1.s3e',
                   'release' : '/Users/danielshir/Work/InnoBell/s3eNextpeerTest/build_test1_xcode/build/Release ARM/test1.s3e',
                 },
         'x86' : {
                   'debug'   : '/Users/danielshir/Work/InnoBell/s3eNextpeerTest/build_test1_xcode/build/Debug/test1.s86',
                   'release' : '/Users/danielshir/Work/InnoBell/s3eNextpeerTest/build_test1_xcode/build/Release/test1.s86',
                 },
        }
    assets = assets['Default']

default = DefaultConfig()
