#ifndef I3D_ARCH_X86
#   define I3D_ARCH_X86 1
#endif
#ifndef I3D_OS_IPHONE
#   define I3D_OS_IPHONE 1
#endif
#ifndef I3D_PLATFORM_IPHONE
#   define I3D_PLATFORM_IPHONE 1
#endif
#ifndef IW_ASSERTION_CHANNEL_NEXTPEER
#   define IW_ASSERTION_CHANNEL_NEXTPEER 1
#endif
#ifndef IW_MKF_EDK
#   define IW_MKF_EDK 1
#endif
#ifndef IW_MKF_S3ENEXTPEER_BUILD
#   define IW_MKF_S3ENEXTPEER_BUILD 1
#endif
#ifndef IW_PLATFORM_IPHONE
#   define IW_PLATFORM_IPHONE 1
#endif
#ifndef IW_SDK
#   define IW_SDK 1
#endif
#ifndef IW_TRACE_CHANNEL_NEXTPEER
#   define IW_TRACE_CHANNEL_NEXTPEER 1
#endif
#ifndef IW_TRACE_CHANNEL_NEXTPEER_VERBOSE
#   define IW_TRACE_CHANNEL_NEXTPEER_VERBOSE 2
#endif
#ifndef S3E_BUILD_EXT
#   define S3E_BUILD_EXT 1
#endif
#ifndef S3E_EXT_NEXTPEER
#   define S3E_EXT_NEXTPEER 1
#endif
#ifndef __IPHONE_OS_VERSION_MIN_REQUIRED
#   define __IPHONE_OS_VERSION_MIN_REQUIRED 2000
#endif
