/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "s3eNextpeer_autodefs.h"
#include "s3eEdk.h"
#include "s3eNextpeer.h"
//Declarations of Init and Term functions
extern s3eResult s3eNextpeerInit();
extern void s3eNextpeerTerminate();


void s3eNextpeerRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[3];
    funcPtrs[0] = (void*)s3eNextpeerInitWithProductKeyAndDelegatesContainer;
    funcPtrs[1] = (void*)s3eNextpeerLaunchDashboard;
    funcPtrs[2] = (void*)s3eNextpeerShutDown;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[3] = { 0 };

    /*
     * Register the extension
     */
    s3eEdkRegister("s3eNextpeer", funcPtrs, sizeof(funcPtrs), flags, s3eNextpeerInit, s3eNextpeerTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eNextpeerStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eNextpeerRegisterExt;
    return 0;
}

int g_s3eNextpeerVal = s3eNextpeerStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eNextpeerRegisterExt();
}
#endif

#endif
